{
    "name": "ShipStation Connector",
    "version": "18.0.1.0.0",
    "summary": "ShipStation connector with instances, sync data, reports, and dashboard",
    "category": "Inventory",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "sale_management",
        "stock",
        "delivery",
        "contacts",
    ],
    "data": [
        "security/shipstation_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/shipstation_instance_view.xml",
        "views/shipstation_field_mapping_views.xml",
        "views/shipstation_order_sync_view.xml",
        "views/shipstation_customer_sync_view.xml",
        "views/shipstation_shipment_sync_view.xml",
        "views/shipstation_product_sync_view.xml",
        "views/shipstation_inventory_view.xml",
        "views/shipstation_category_sync_view.xml",
        "views/shipstation_attribute_sync_view.xml",
        "views/shipstation_report_view.xml",
        "views/shipstation_sync_log_view.xml",
        "views/shipstation_res_config_settings_view.xml",
        "views/shipstation_dashboard_action.xml",
        "views/shipstation_actions.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "shipstation_connector/static/src/css/shipstation_dashboard.css",
            "shipstation_connector/static/src/scss/chatbot.scss",
            "shipstation_connector/static/src/js/shipstation_dashboard.js",
            "shipstation_connector/static/src/js/chatbot.js",
            "shipstation_connector/static/src/xml/chatbot.xml",
            "shipstation_connector/static/src/xml/shipstation_dashboard_templates.xml",
        ],
    },
    "installable": True,
    "application": True,
}
